{{- if .Values.frontend.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "tactical-display.fullname" . }}-frontend
  annotations:
    haproxy.router.openshift.io/timeout: 300s
  labels:
    {{- include "tactical-display.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if .Values.frontend.route.host }}
  host: {{ .Values.frontend.route.host }}
  {{- end }}
  to:
    kind: Service
    name: tactical-frontend
    weight: 100
  port:
    targetPort: http
  {{- if .Values.frontend.route.tls.enabled }}
  tls:
    termination: {{ .Values.frontend.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.frontend.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
